# Generated by Django 3.2.25 on 2025-04-09 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Games with Hard Complexity', 'Games with Hard Complexity'), ('Pricing Inquiry', 'Pricing Inquiry'), ('Trouble buying the game', 'Trouble buying the game'), ('Account Issues', 'Account Issues'), ('Other', 'Other')], max_length=254)),
                ('message', models.TextField(max_length=1024)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Requests',
            },
        ),
    ]
