# Generated by Django 3.2.25 on 2025-03-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_playing_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
